In [26]:
print ("Hello World")

Hello World

In [27]:
import pandas as pd

In [28]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns = ["A","B","C"],index =["E","F","G"] )

In [29]:
df.head()

   A  B  C
E  1  2  3
F  4  5  6
G  7  8  9

In [30]:
df.head(1)

   A  B  C
E  1  2  3

In [31]:
df.tail(2)

   A  B  C
F  4  5  6
G  7  8  9

In [32]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [33]:
df.index

Index(['E', 'F', 'G'], dtype='str')

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, E to G
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [40]:
coffee = pd.read_csv('complete-pandas-tutorial/warmup-data/coffee.csv')

In [42]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [43]:
coffee.index

RangeIndex(start=0, stop=14, step=1)

In [44]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold'], dtype='str')

In [45]:
results = pd.read_parquet(r'C:\Users\aumas\Desktop\Python\Pandas\complete-pandas-tutorial\data\results.parquet')

In [47]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [57]:
olymics_data = pd.read_excel('complete-pandas-tutorial\data\olympics-data.xlsx', sheet_name='results')

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\aumas\AppData\Local\Temp\ipykernel_19964\3048564391.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  olymics_data = pd.read_excel('complete-pandas-tutorial\data\olympics-data.xlsx', sheet_name='results')

In [58]:
olymics_data.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [51]:
olymics_data.index

RangeIndex(start=0, stop=145500, step=1)

In [53]:
olymics_data.columns

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date'],
      dtype='str')

In [56]:
olymics_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [94]:
coffee.sample(10,random_state=1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [97]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [107]:
coffee.loc[0:2,["Day","Units Sold"]]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

In [108]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [117]:
coffee.loc[3,"Coffee Type"] = "Espresso"

In [118]:
coffee

          Day Coffee Type  Units Sold
0      Monday       Latte          25
1      Monday       Latte          10
2     Tuesday       Latte          30
3     Tuesday    Espresso          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [126]:
coffee.at[13,"Units Sold"]

np.int64(35)

In [127]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [130]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   14 non-null     int64
dtypes: int64(1), str(2)
memory usage: 656.0 bytes

In [136]:
sort = coffee.sort_values("Units Sold")

In [138]:
sort.head()

         Day Coffee Type  Units Sold
1     Monday       Latte          10
3    Tuesday    Espresso          20
0     Monday       Latte          25
5  Wednesday       Latte          25
2    Tuesday       Latte          30

In [143]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday       Latte          30
7    Thursday       Latte          30
0      Monday       Latte          25
5   Wednesday       Latte          25
3     Tuesday    Espresso          20
1      Monday       Latte          10

In [144]:
bios.head

NameError: name 'bios' is not defined

In [147]:
bios = pd.read_csv(r'C:\Users\aumas\Desktop\Python\Pandas\complete-pandas-tutorial\data\bios.csv')

In [148]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [172]:
height = bios.loc[bios['height_cm']>=219, ["name","height_cm"]]

In [173]:
height_sort = height.sort_values(["height_cm"] , ascending=False)

In [174]:
height_sort

                      name  height_cm
89070             Yao Ming      226.0
6978       Arvydas Sabonis      223.0
5781        Tommy Burleson      223.0
120266        Zhang Zhaoxu      221.0
5673        Gunther Behnke      221.0
89075       Roberto Dueñas      221.0
5089    Viktor Pankrashkin      220.0
7188    Vladimir Tkachenko      220.0
6504           Luc Longley      220.0
107408    Peter John Ramos      219.0
118676     Dmitry Musersky      219.0

In [ ]:
height_sort.index

<bound method Index.identical of Index([89070, 6978, 5781, 120266, 5673, 89075, 5089, 7188, 6504, 107408,
       118676],
      dtype='int64')>

In [181]:
bios[(bios['height_cm' ]< 150) & (bios['weight_kg']> 60 )]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN
14918,15019,Daniel Kaswanga,1960-01-01,NaN,NaN,NaN,Malawi,138.0,67.0,NaN
32203,32444,Khamis Bashir,NaN,NaN,NaN,NaN,Kuwait,140.0,70.0,NaN
43257,43591,Said Al-Khatry,1947-01-01,NaN,NaN,NaN,Oman,132.0,66.0,NaN
123382,125570,Tuau Lapua,1991-04-15,NaN,NaN,NaN,Tuvalu,140.0,62.0,NaN

In [182]:
import numpy as np

In [184]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday       Latte          25
1     Monday       Latte          10
2    Tuesday       Latte          30
3    Tuesday    Espresso          20
4  Wednesday    Espresso          35

In [185]:
coffee['price'] = 4.99

In [187]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday       Latte          25   4.99
1     Monday       Latte          10   4.99
2    Tuesday       Latte          30   4.99
3    Tuesday    Espresso          20   4.99
4  Wednesday    Espresso          35   4.99

In [189]:
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso',3.99,4.99)

In [190]:
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday       Latte          25   4.99       4.99
1     Monday       Latte          10   4.99       4.99
2    Tuesday       Latte          30   4.99       4.99
3    Tuesday    Espresso          20   4.99       3.99
4  Wednesday    Espresso          35   4.99       3.99

In [193]:
coffee.drop(columns=3)

KeyError: '[3] not found in axis'

In [197]:
final = coffee.drop(columns="price")

In [198]:
final.head()

         Day Coffee Type  Units Sold  new_price
0     Monday       Latte          25       4.99
1     Monday       Latte          10       4.99
2    Tuesday       Latte          30       4.99
3    Tuesday    Espresso          20       3.99
4  Wednesday    Espresso          35       3.99